# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sHVxtLXvdqhLEWSyfisIwaZFauk_xco2
"""

# Create app.py (Flask web app)
with open("app.py", "w") as f:
    f.write(""")
from flask import Flask, request, render_template
import socket
from common_ports import ports_and_services

app = Flask(__name__)

def get_open_ports(target, port_range):
    open_ports = []
    try:
        ip = socket.gethostbyname(target)
    except socket.gaierror:
        return "Error: Invalid hostname"
    for port in range(port_range[0], port_range[1]+1):
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.settimeout(1)
        result = sock.connect_ex((ip, port))
        if result == 0:
            open_ports.append(port)
        sock.close()
    return open_ports

@app.route("/", methods=["GET", "POST"])
def index():
    if request.method == "POST":
        target = request.form.get("target")
        start = int(request.form.get("start_port"))
        end = int(request.form.get("end_port"))
        open_ports = get_open_ports(target, [start, end])
        results = [(port, ports_and_services.get(port, "unknown")) for port in open_ports]
        return render_template("index.html", target=target, results=results)
    return render_template("index.html", target=None)

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=10000)
