# -*- coding: utf-8 -*-
"""commonports.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_0Go3t6r7uHFD7eFAahu05izHMxxlN9S
"""

# Create common_ports.py (dictionary of known ports)
with open("common_ports.py", "w") as f:
    f.write("""
ports_and_services = {
    20: "ftp-data",
    21: "ftp",
    22: "ssh",
    23: "telnet",
    25: "smtp",
    53: "dns",
    80: "http",
    110: "pop3",
    143: "imap",
    443: "https",
    8080: "http-proxy"
}
""")